/**
 * API Module Exports
 *
 * This module provides:
 * - api: Base API client with auth/language headers
 * - ApiError: Custom error class for API errors
 * - Type-safe API helpers (when generated.ts is available)
 */

// Base client
export {api, apiCall, ApiError} from './client';
export type {ApiCallOptions} from './client';

// Re-export generated types when available
// These will be generated by: ./dev.sh api:client
// export * from './generated';
